language: c

env:
  # standard builds
  - CC=gcc
  - CC=clang
  # cross-compile using mingw
  - CC= PLATFORM="mingw32" ARCH="x86"
  - CC= PLATFORM="mingw32" ARCH="x86_64"

script: ./travis-ci-build.sh

before_install:
  - sudo apt-get update -qq
  - sudo apt-get remove -qq -y mingw32
  - sudo apt-get install -q -y libgl1-mesa-dev libsdl1.2-dev mingw-w64

notifications:
  irc: "irc.freenode.org#spearmint"
  on_success: change
  on_failure: always
